name 'rm-test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rm-test'
long_description 'Installs/Configures rm-test'
version '0.1.0'
issues_url 'some_url'
source_url 'some_url'
depends 'openssl'
depends 'sudo'
depends 'rvm'
depends 'users'
depends 'postgresql'
depends 'database'
depends 'nginx'
depends 'simple_iptables'
